"""Cross-lingual target-text pool for meta-training and evaluation.

Each language has 60 short, declarative sentences (5–12 words) covering common
phonotactic diversity (open/closed syllables, voiced/unvoiced onsets, tonal
contour variation for Chinese, accented vowels for Spanish).  Two distinct
pools per language let us sample support text ``t`` and a *different* query
text ``t_q`` per episode (§5.5 of the plan).

Source: hand-curated for this study; designed to avoid copyrighted material.
"""
from __future__ import annotations

import random
from typing import Dict, List

EN_SENTENCES: List[str] = [
    "The morning sunlight filtered through the open kitchen window.",
    "She placed the warm mug carefully beside the worn brown notebook.",
    "Children played quietly in the small park near the library.",
    "Heavy rain drummed against the tin roof for hours.",
    "Old photographs in the wooden box told a hundred stories.",
    "The chef tasted the soup and added a pinch of salt.",
    "Travelers waited patiently as the storm slowly passed overhead.",
    "Late at night, the city lights flickered like distant stars.",
    "A small dog barked loudly at every passing bicycle.",
    "Three friends shared a quiet dinner under the wooden gazebo.",
    "The painter mixed the colors until the shade felt right.",
    "Mountain trails wound gently between tall ancient pine trees.",
    "She practiced the violin every evening after finishing her homework.",
    "The bakery filled the corner street with the smell of fresh bread.",
    "Wind chimes near the balcony rang softly in the autumn breeze.",
    "A polite waiter brought hot tea and a plate of cookies.",
    "Their old radio crackled when the thunderstorm rolled in.",
    "The library closed early because of an unexpected power outage.",
    "Snow began to fall just as the church bells rang.",
    "He carefully wrapped the gift in shiny silver paper.",
    "Several boats drifted lazily across the calm summer lake.",
    "The teacher explained the math problem twice for clarity.",
    "Their grandmother always told the funniest bedtime stories.",
    "Bright fireworks lit the harbor sky on New Year's Eve.",
    "A blue jay landed on the windowsill and tilted its head.",
    "He read the newspaper aloud while sipping black coffee.",
    "The runner adjusted her shoes before the morning marathon.",
    "Tall buildings cast long cool shadows across the empty plaza.",
    "A gentle melody played from the cafe at the corner.",
    "The astronomer pointed at a faint star above the trees.",
    "Quiet footsteps echoed in the long marble hallway.",
    "The market was full of fresh vegetables and ripe fruit.",
    "She wrote a long letter to her best childhood friend.",
    "Birds gathered on the wire as the sun went down.",
    "The boy held a red balloon tightly in his hand.",
    "After dinner they walked slowly along the riverbank together.",
    "Faded posters covered the brick wall of the old theatre.",
    "Their cat curled up on the soft cushion by the window.",
    "Workers repaired the broken bench in the central garden.",
    "A small bell rang each time the shop door opened.",
    "Friendly neighbors greeted each other across the wooden fence.",
    "Heavy fog rolled in from the sea early that morning.",
    "She found an old map tucked inside the dusty atlas.",
    "Distant church bells marked the slow turning of the day.",
    "The waiter recommended the daily fish stew with bread.",
    "Children carried colorful kites along the windy beach.",
    "The musician tuned his guitar before the first set.",
    "An old clock ticked steadily in the silent waiting room.",
    "The hiker paused to admire the wide green valley below.",
    "Fresh paint dried slowly on the kitchen cabinets.",
    "A polite stranger offered directions to the train station.",
    "The river bent gently before reaching the small bridge.",
    "Soft jazz played from the corner of the bookshop.",
    "She remembered the recipe her mother had written down.",
    "Two horses grazed peacefully behind the wooden fence.",
    "The gardener planted tulips along the curving path.",
    "Coffee shops on the avenue stayed open until midnight.",
    "He whispered the secret to his sister in the dark.",
    "An old film projector hummed softly in the museum corner.",
    "She thanked the librarian for helping her find the book.",
]

ZH_SENTENCES: List[str] = [
    "今天天气真好，我们一起去公园散步吧。",
    "他在窗边静静地看着外面的雨。",
    "妈妈做的红烧肉真的非常好吃。",
    "夜晚的星空让人想起遥远的童年。",
    "她正在认真练习刚学的钢琴曲。",
    "我们沿着河边走了一段很长的路。",
    "老师耐心地讲解每一道数学题。",
    "院子里的桂花开得格外香。",
    "他每天都会去图书馆读书。",
    "孩子们在草地上快乐地奔跑。",
    "雪花静悄悄地落在屋顶上。",
    "她在窗台上摆了几盆绿色的植物。",
    "傍晚的小镇显得格外宁静。",
    "他们在山顶看着日落慢慢升起。",
    "厨师把汤里加了一点儿盐。",
    "图书馆因为停电而提前关门了。",
    "小猫蜷缩在沙发上睡得很香。",
    "他细心地用银色的纸把礼物包好。",
    "妈妈把刚出炉的面包放在桌上。",
    "他们在湖边一起拍了一张合影。",
    "夜深了，街角的灯还亮着。",
    "她把那本旧相册放回了书架。",
    "公园里的孩子们正在放风筝。",
    "雨水敲在屋顶上发出清脆的声音。",
    "弟弟把书包整齐地放在床边。",
    "傍晚的风带着一丝凉意。",
    "老人坐在长椅上看着远处的山。",
    "她在炉子上煮了一锅热腾腾的粥。",
    "树叶在秋风中轻轻地落下。",
    "他在桌上摆了一杯热茶和一本书。",
    "我们在小巷里发现了一家老书店。",
    "邻居家的狗每天清晨都会叫。",
    "她把信折好放进了信封里。",
    "他从口袋里掏出了一把旧钥匙。",
    "学生们认真地准备着明天的演讲。",
    "她把窗帘拉开让阳光照进房间。",
    "厨房里飘来了红烧肉的香味。",
    "他在工地上工作了一整天。",
    "她把那张老照片贴在了墙上。",
    "我们在湖边租了一条小木船。",
    "夜里下了一场很大的雷雨。",
    "他用钢笔在本子上写了几行字。",
    "她把书放在床头慢慢翻看。",
    "院子里的菊花开得正盛。",
    "他每天清早都要去跑步。",
    "孩子们在河边捡了很多漂亮的石头。",
    "她在阳台上晾晒了一床被子。",
    "他在演讲前认真地准备了稿子。",
    "妈妈把刚煮好的饺子端上了桌。",
    "他们在书店里坐了一个下午。",
    "夜风轻轻地吹过窗外的树枝。",
    "她在桌上摆好了热气腾腾的饭菜。",
    "村口的大树下站着几个孩子。",
    "雨过天晴，空气格外清新。",
    "他从抽屉里拿出一支铅笔。",
    "他们在山林里听到了鸟的鸣叫。",
    "小狗在院子里追着自己的影子。",
    "他把窗户打开让微风吹进来。",
    "她在厨房里忙着准备晚饭。",
    "他在书房里整理了很久的资料。",
]

ES_SENTENCES: List[str] = [
    "El sol de la mañana entraba por la ventana de la cocina.",
    "Ella colocó la taza tibia junto al cuaderno marrón.",
    "Los niños jugaban tranquilamente en el parque cerca de la biblioteca.",
    "La lluvia golpeaba el techo de hojalata durante horas.",
    "Las viejas fotografías guardaban cientos de historias.",
    "El cocinero probó la sopa y añadió una pizca de sal.",
    "Los viajeros esperaron pacientes a que pasara la tormenta.",
    "Por la noche, las luces de la ciudad parpadeaban como estrellas distantes.",
    "Un perrito ladraba a cada bicicleta que pasaba.",
    "Tres amigos cenaron en silencio bajo la pérgola de madera.",
    "El pintor mezcló los colores hasta encontrar el tono correcto.",
    "Los senderos subían suavemente entre pinos antiguos.",
    "Ella practicaba el violín cada tarde después de los deberes.",
    "La panadería llenaba la calle con olor a pan recién hecho.",
    "Las campanillas del balcón sonaban con la brisa de otoño.",
    "Un camarero amable trajo té caliente y un plato de galletas.",
    "Su vieja radio crujía cuando llegaba la tormenta.",
    "La biblioteca cerró temprano por un corte de electricidad.",
    "La nieve empezó a caer justo cuando sonaron las campanas.",
    "Envolvió el regalo con cuidado en papel plateado.",
    "Varios botes flotaban en el lago tranquilo.",
    "El profesor explicó el problema de matemáticas dos veces.",
    "Su abuela siempre contaba las historias más divertidas.",
    "Los fuegos artificiales iluminaron el cielo en la víspera de Año Nuevo.",
    "Un pájaro azul aterrizó en la ventana e inclinó la cabeza.",
    "Él leía el periódico mientras tomaba café negro.",
    "La corredora ajustó sus zapatillas antes del maratón.",
    "Los edificios altos dejaban largas sombras en la plaza.",
    "Una melodía suave salía del café de la esquina.",
    "El astrónomo señaló una estrella tenue sobre los árboles.",
    "Pasos silenciosos resonaron en el pasillo de mármol.",
    "El mercado estaba lleno de verduras frescas y fruta madura.",
    "Ella escribió una larga carta a su mejor amiga de la infancia.",
    "Los pájaros se reunieron en el cable mientras se ponía el sol.",
    "El niño sostenía firmemente un globo rojo.",
    "Después de cenar caminaron despacio junto al río.",
    "Carteles descoloridos cubrían la pared del viejo teatro.",
    "Su gato se enroscó en el cojín junto a la ventana.",
    "Los trabajadores reparaban el banco roto del jardín central.",
    "Una pequeña campana sonaba cada vez que se abría la tienda.",
    "Los vecinos se saludaban por encima de la valla de madera.",
    "Una densa niebla llegó del mar temprano por la mañana.",
    "Encontró un mapa antiguo dentro del atlas polvoriento.",
    "Las campanas lejanas marcaban el paso lento del día.",
    "El camarero recomendó el guiso de pescado del día.",
    "Los niños llevaban cometas coloridas por la playa ventosa.",
    "El músico afinó su guitarra antes del primer concierto.",
    "Un reloj antiguo marcaba el tiempo en la sala silenciosa.",
    "El excursionista se detuvo a admirar el ancho valle verde.",
    "La pintura fresca se secaba lentamente en los muebles de la cocina.",
    "Un desconocido amable indicó el camino a la estación.",
    "El río se curvaba suavemente antes de llegar al puente.",
    "Sonaba jazz suave en el rincón de la librería.",
    "Recordó la receta que su madre había escrito.",
    "Dos caballos pastaban tranquilos detrás de la cerca.",
    "El jardinero plantó tulipanes a lo largo del camino.",
    "Las cafeterías de la avenida estaban abiertas hasta la medianoche.",
    "Él le susurró el secreto a su hermana en la oscuridad.",
    "Un viejo proyector zumbaba suavemente en el rincón del museo.",
    "Agradeció al bibliotecario por ayudarle a encontrar el libro.",
]


POOLS: Dict[str, List[str]] = {"en": EN_SENTENCES, "zh": ZH_SENTENCES, "es": ES_SENTENCES}


def sample_pair(lang: str, rng: random.Random) -> tuple[str, str]:
    """Sample (support_text, query_text) — two distinct sentences in the given language."""
    pool = POOLS[lang]
    a, b = rng.sample(pool, 2)
    return a, b


def sample_one(lang: str, rng: random.Random) -> str:
    return rng.choice(POOLS[lang])


def n_sentences(lang: str) -> int:
    return len(POOLS[lang])
